---
deployment:
  tasks:
    - export DEPLOYPATH=/home/njordhotel/public_html
    - /bin/cp -R *.html $DEPLOYPATH/
    - /bin/cp -R *.php $DEPLOYPATH/
    - /bin/cp -R *.png $DEPLOYPATH/
    - /bin/cp -R css $DEPLOYPATH/
    - /bin/cp -R js $DEPLOYPATH/
    - /bin/cp -R fonts $DEPLOYPATH/
    - /bin/cp -R assets $DEPLOYPATH/
    - /bin/cp .htaccess $DEPLOYPATH/ 2>/dev/null || true
